config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :registered_applications

  get 'about' => 'welcome#about'

  root 'welcome#index'

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  # Skip CSRF protection in development
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  before_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application.present?
      @event = registered_application.events.build(event_params)
      if @event.save
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = current_user.registered_applications
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = current_user.registered_applications.build(registered_application_params)

    if @registered_application.save
      flash[:notice] = "Your application is now registered."
      redirect_to [@registered_application]
    else
      flash.now[:alert] = "There was an error in registering your app. Please try again."
      render :new
    end
  end

  def show
    @registered_application = current_user.registered_applications.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  def destroy
    @registered_application = current_user.registered_applications.find(params[:id])

    if @registered_application.destroy
      flash[:notice] ="\"#{@registered_application.name}\" was de-registered successfully."
      redirect_to registered_applications_path
    else
      flash.now[:alert] = "There was an error de-registering your app. Please try again."
      render :show
    end
  end

  private
  def registered_application_params
    params.require(:registered_application).permit(:name, :url, :private)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
  	<div class="container">
  		<ul class="nav nav-tabs">
  			<li><%= link_to "Home", root_path %></li>
  			<li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Apps", registered_applications_path %></li>
        <% end %>

        <div class="pull-right-user-info">
          <% if user_signed_in? %>
            <div class="pull-right">
              <ul class="nav nav-tabs", style="border-bottom:0px;">
                <li class="username">Signed in as: <strong><%= current_user.email %></strong></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
              </ul>
            </div>
          <% else %>
            <div class="pull-right">
              <ul class="nav nav-tabs", style="border-bottom:0px;">
                <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
              </ul>
            </div>
          <% end %>
        </div>
  		</ul>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    	<%= yield %>
    </div>

  </body>
</html>

app/views/registered_applications/edit.html.erb
<h1>Edit Your Registered App</h1>
<div class="row">
	<div class="col-md-8">
		<%= form_for @registeredapp do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control', placeholder: "Enter the site's name here" %>
			</div>
			<div class="form-group">
				<%= f.label :URL %>
				<%= f.text_field :url, class: 'form-control', placeholder: "Enter the site's URL here- no 'http' required!" %>
			</div>
			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

app/views/registered_applications/index.html.erb
<h1>My Registered Apps</h1>

<div class="row">
	<div class="col-md-8">
		<% if @registered_applications.any? %>
			<% @registered_applications.each do |app| %>
				<div class="media">
					<div class="media-body">
						<h4 class="media-heading">
							<%= link_to app.name, app %>
						</h4>
					</div>
				</div>
			<% end %>
		<% else %>
			<p>You haven't registered any apps yet.</p>
		<% end %>
	</div>
	<div class="col-md-4", style="padding-top:10px;">
		<%= link_to "Register a new app", new_registered_application_path, class: 'btn btn-success' %>
	</div>
</div>

app/views/registered_applications/new.html.erb
<h1>New App Registration</h1>

<div class="row">
	<div class="col-md-8">
		<%= form_for @registered_application do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control', placeholder: "Enter the site's name here" %>
			</div>
			<div class="form-group">
				<%= f.label :url %>
				<%= f.text_field :url, class: 'form-control', placeholder: "Enter the site's URL here- no 'http' required!" %>
			</div>
			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

app/views/registered_applications/show.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi" %>

<h1><%= @registered_application.name %></h1>

<div class="row">
  <div class="col-md-8">
    <p> <%= @registered_application.url %>
      <%= link_to "Remove Registration", @registered_application, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to remove this app from registration?'} %> </p>
       <%= pie_chart @registered_application.events.group(:name).count %>
       <%= line_chart @registered_application.events.group_by_day(:created_at).count %>

    </div>

  </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Blocmetrics</h1>
<p>An analytic service to track events on websites.</p>